version: '3.7'
services:
  python-server:
    build: .
    ports:
      - 8888:8888
    volumes:
      - .:/app
    tty: true
    command: poetry run jupyter lab --allow-root --ip=0.0.0.0 --LabApp.token=""
